### ISSUE TITLE
Coin Desk api - System.FormatException - Version 0.0.5

### ISSUE THREAD

**Issue by samirissa00** [TheRetroMike/HiveOSProfitSwitcher#4]
Hi , 

i´m compiling from source code in  a test 
the coin desk api json return :

{
  "time": {
    "updated": "Aug 22, 2022 22:53:00 UTC",
    "updatedISO": "2022-08-22T19:53:00-03:00",
    "updateduk": "Aug 22, 2022 at 23:53 BST"
  },
  "disclaimer": "This data was produced from the CoinDesk Bitcoin Price Index (USD). Non-USD currency data converted using hourly conversion rate from openexchangerates.org",
  "chartName": "Bitcoin",
  "bpi": {
    "USD": {
      "code": "USD",
      "symbol": "&#36;",
      "rate": "21,172.3014",
      "description": "United States Dollar",
      "rate_float": 21172.3014
    },
    "GBP": {
      "code": "GBP",
      "symbol": "&pound;",
      "rate": "17,691.4057",
      "description": "British Pound Sterling",
      "rate_float": 17691.4057
    },
    "EUR": {
      "code": "EUR",
      "symbol": "&euro;",
      "rate": "20,624.9128",
      "description": "Euro",
      "rate_float": 20624.9128
    }
  }
}

+++

"rate_float": 21172.3014

+++

the  code to map that is :

btcPrice = Convert.ToDouble(btcMarketData?.bpi?.USD?.rate?.Value ?? 0.01);

i´m getting a error here  on " rate " word .

"rate_float" in json and  "rate " in code ... 

Unhandled Exception: System.FormatException:

when i change to rate_float it woks fine in windows from Source, but version 0.0.5  in linux Hive OS is not getting this error.

Need I change that  in development on windows ?

Thanks !!

**Comment by 05sonicblue** [comment]
I just tested it with the latest code base in Windows using Visual Studio and I'm not getting any errors from the api using the rate field:

![image](https://user-images.githubusercontent.com/1271856/186040499-963af00b-6fdd-48bd-919f-6b89253bd9bf.png)

**Comment by samirissa00** [comment]
I think that the problem is regional settings of windows   !    I'm using metric system and decimals are ", " and thousands "."    !   Sorry  and Thanks again !  I need use this in source  :

using System.Globalization;
... 
CultureInfo us = new CultureInfo("en-US");
.... 

and it works !!
