### ISSUE TITLE
Date/Time Stamp

### ISSUE THREAD

**Issue by luizgperez1983** [TheRetroMike/HiveOSProfitSwitcher#5]
Suggestion: include a date/time stamp in the first return line to help in log

**Comment by lfsamp** [comment]
My suggestion is add timestamp in all lines of the logs. That give us idea if the PS runs as expected. Like we setup in `crontab`

**Comment by 05sonicblue** [comment]
> My suggestion is add timestamp in all lines of the logs. That give us idea if the PS runs as expected. Like we setup in `crontab` Also, only show latest version when it changes.

Both of these were addressed in the latest version.

**Comment by lfsamp** [comment]
> > My suggestion is add timestamp in all lines of the logs. That give us idea if the PS runs as expected. Like we setup in `crontab` Also, only show latest version when it changes.
> 
> Both of these were addressed in the latest version.

I did not see in the latest version:
![image](https://user-images.githubusercontent.com/16020586/188721453-556f79c4-66ae-48c4-bbce-f149265d266c.png)

Did you mean it is coming in the next version?
