### ISSUE TITLE
crontab not start

### ISSUE THREAD

**Issue by marosalv** [TheRetroMike/HiveOSProfitSwitcher#8]
I had some problems with CRON not recognizing the 0/15 * * * * syntax, I solved the problem by replacing it with 0,15,30,45 * * * * (and so on) and it started working normally again. I hope it will be updated in the next versions, or it was a problem with my version of CRON (3.0 it would seem).

**Comment by 05sonicblue** [comment]
I fixed it in the installer script for both the profit switcher and the updater a few hours ago. The correct format should be */15 * * * * for it to run every 15 minutes.
